# server地址，一般不用修改
HOST: '0.0.0.0'

# http端口
HTTP_PORT: 80
# https端口
HTTPS_PORT: 443

# 使用https
HTTPS: false
# http重定向https
HTTP_TO_HTTPS: true
# ssl证书crt文件路径
CA_CERTIFICATE: './config/SSL/certificate.crt'
# ssl证书key文件路径
CA_PRIVATE: './config/SSL/private.key'

# 启用 CORS 头部
CROSS_DOMAIN: true

# 信任代理
TRUST_PROXY: false
# 信任来自以下IP的代理
TRUST_PROXY_IP:
  - '0.0.0.0'
  - '123.123.123.123'

# 公众访问地址
PUBLIC_ADDRESS: 'http://example.com/'