# 站点信息
SITE_NAME: 'Hlhsの小破站' #标题
SITE_ANTHOR: 'Hlhs' # 作者
SITE_KEYWORDS: 'hlhs home page' # 关键词
SITE_DES: '除了时间，什么也没留下，风带来故事的种子，时间使其发芽。' # 站点简介
SITE_URL: 'Hlhs.com' # 站点地址
SITE_MAIN_LOGO: './images/icon/logo.png' # 主页图标, /public相对路径

# 简介文本
DESC_HELLO: 'Hello World !'
DESC_TEXT: '你们觉得彭于晏很帅吗，我觉得还行吧，可能是在一起久了没什么感觉了'
DESC_HELLO_OTHER: 'Oops !'
DESC_TEXT_OTHER: '哎呀，这都被你发现了（ 再点击一次可关闭 ）'

# 壁纸数量，按顺序从1开始background前缀
BACKGROUND_MAX: 11

# 社交链接
## 请在 config/page/home/socialLinks.json 文件中配置

# 网站链接
## 请在 siteLinks.json 文件中配置
## 网站链接的图标名称可前往 https://www.xicons.org 自行挑选
## 下载后在 config/page/home/siteLinks.json 中引入，/public相对路径
## 图标颜色可在svg代码中`fill`标签修改，如fill: "#fff"

# 天气 Key
## 请前往 高德开放平台注册 Web服务 Key
## 请注意不是 Web端 (JS API)，免费申请，每日上限 5000 次
## 此处提供的服务可能会超量从而无法访问，请自行申请！请自行申请！请自行申请！
## 若此处设为空则调用 教书先生 API https://api.oioweb.cn/doc/weather/GetWeather
WEATHER_KEY: ''

# 建站日期
## 若不需要，请设为空即可
## 请按照 YYYY-MM-DD 格式填写或者仅填写年份 YYYY
SITE_START: '2022-01-01'

# ICP 备案号 例如'粤ICP备2022010100号-1'
## 国内域名主页必须设置, 若不需要，请设为空即可
SITE_ICP: ''

# MetingAPI 地址
SONG_API: "/music/api/meting"
# 歌曲服务器 ( netease: 网易云, tencent: qq音乐 )
## 若使用 QQ 音乐歌单，歌曲数量最好不要超出 50 首
SONG_SERVER: 'netease'
# 播放类型 ( song-歌曲, playlist-播放列表, album-专辑, search-搜索, artist-艺术家 )
SONG_TYPE: 'album'
# 歌曲/歌单ID ( 若无需播放器，请设为空即可 )
SONG_ID: '175676520' # 枫丹音乐专辑